### ISSUE TITLE
Fix broken blogpost link

### ISSUE THREAD

**Issue by armanSingh** [dadepo/Webmuncher#18]
#19 Links referring to documentation in the blogposts are broken. Please update this issue with any new broken links.

1. [Motivation URL](http://geekabyte.blogspot.in/2014/12/a-web-scrapercrawler-in-java-krwkrw.html)
2. [Release Announcement](http://geekabyte.blogspot.in/2015/09/webmuncher-013-released.html) 

If the content has not been deleted, please update the link.

**Comment by armanSingh** [comment]
Created a [pull request](https://github.com/dadepo/Webmuncher/pull/19) with a fix for the above broken URLs.

**Comment by dadepo** [comment]
Thanks!
